version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-apptica-app
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_DATABASE: apptica_test
      DB_USERNAME: root
      DB_PASSWORD: root
    entrypoint: sh -c "php artisan migrate && php-fpm"

  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    restart: unless-stopped
    ports:
      - "9000:80"  # External port 9000 -> nginx inside port 80
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mariadb:10.6
    container_name: laravel-db
    restart: unless-stopped
    ports:
      - "13306:3306"  # Changed from 3306 to 13306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: apptica_test
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
